name: Action Delegator module deployment

on:
  workflow_dispatch:

env:
  RUBY_VERSION: 2.6.6
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bundle_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 1

      - uses: ruby/setup-ruby@master
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Recover Ruby dependency cache
        uses: actions/cache@v2.1.5
        with:
          path: ./vendor/bundle
          key: ${{ runner.OS }}-rubydeps-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-rubydeps-${{ env.cache-name }}-
            ${{ runner.OS }}-rubydeps-
            ${{ runner.OS }}-

      - name: Install Ruby deps
        run: |
          gem install bundler:2.1.4
          bundle install --path vendor/bundle --jobs 4 --retry 3

      - run: |
          bundle update decidim-action_delegator

      - run: |
          bundle exec rails decidim_action_delegator:install:migrations

      - uses: EndBug/add-and-commit@v7
        with:
          add: Gemfile.lock db/
          branch: master
